### PR TITLE
Fix for Issue #12

### PR DESCRIPTION
**Pull request by mrzepka**
Sorry that there are 3 commits, I had some issues fighting git and didn't know how to remove the other commits. The only change in the files is r.header -> r.headers for the 429 response. 

You can hold off merging this until whenever, I'm still testing it locally.

### CODE REVIEW

**Comment by mrzepka** [comment]
I added 5 to the sleep function input due to the comments I put in the issue thread.

Essentially there were some edge cases where the sleep was getting a negative value after two consecutive timeouts.

**Comment by mrzepka** [comment]
After more use of the script I finally triggered some timeouts, it looks like adding 5 to the delta resolved the issue. Not sure if we want to try 3 seconds or if 5 is fine.

**Comment by jasondilworth56** [comment]
My gut feeling is that this feels a bit smelly, and that there should be a reason that this goes negative that we can sort out. Presumably this can only go negative when we're close to the reset anyway, so would something like `time.sleep(max(delta.total_seconds(), 1)` work? 

That gives us a minimum of one second of sleep on a `429` response, ensures that the sleep is always positive, but minimises those times where -0.1 turns into +4.9 and gives us nearly 5 seconds of unnecessary sleep. Not sure it's much better, to be honest!

**Comment by mrzepka** [comment]
When I tried +1 I still got caught on a few edge cases. I'll run it again and see if I can reproduce. I think I had more context on the issue itself than the comments for the pull request here.

**Comment by NoHeDidnt** [comment]
> My gut feeling is that this feels a bit smelly, and that there should be a reason that this goes negative that we can sort out.

This goes negative if the `reset_datetime` is in the past, because it assumes `reset_datetime` is in the future.
We should check for that before calculating `delta`. (e.g.
`if reset_datetime > datetime.now():`)
That way we can avoid the issues with a negative `delta`, without any unnecessary delays.

**Comment by mrzepka** [comment]
I had to wrestle with github but @NoHeDidnt had a good idea so I implemented that. Should pretty clearly avoid any negative sleeps.

**Comment by jasondilworth56** [comment]
Thanks for this Matt, I've been swamped but will get onto getting this into the next release early next week. I appreciate the effort.

**Pull request merged**
